### ISSUE TITLE
please version sha256-simd 

### ISSUE THREAD

**Issue by aviau** [minio/sha256-simd#10]
Hello,

Could you please tag this repository?

I am the Debian Maintainer for this project and tags would help Debian keep up with new releases/bugfixes.

See:
- http://semver.org/
- http://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by harshavardhana** [comment]
@aviau optimized changes are part of  upstream https://golang.org/pkg/crypto/sha256/ i am not sure if packaging is needed for this anymore.

**Comment by calmh** [comment]
Hmm, really? Since when, in 1.8? That worries me given #6...

**Comment by harshavardhana** [comment]
> Hmm, really? Since when, in 1.8? That worries me given #6...

It is already present since go 1.7 AFAIK.

**Comment by calmh** [comment]
Certainly not. The optimizations in this package are vastly superior to Go 1.7 stdlib.

**Comment by harshavardhana** [comment]
Now back to semver question we are not planning to do that projects depending on this vendorize and go tools are perfectly capable of picking things up. 

Feel free to choose a version @aviau for debian packaging.
