### ISSUE TITLE
duplicate constants error on go devel +2481481

### ISSUE THREAD

**Issue by zchee** [minio/sha256-simd#11]
When I try to `go get`, the following error occurred.

```sh
> go get -u -v -x github.com/minio/sha256-simd
github.com/minio/sha256-simd (download)
cd .
git clone https://github.com/minio/sha256-simd /Users/zchee/go/src/github.com/minio/sha256-simd
cd /Users/zchee/go/src/github.com/minio/sha256-simd
git submodule update --init --recursive
cd /Users/zchee/go/src/github.com/minio/sha256-simd
git show-ref
cd /Users/zchee/go/src/github.com/minio/sha256-simd
git submodule update --init --recursive
WORK=/var/folders/kk/nlghjzs913d70lnngdp8bhsr0000gn/T/go-build073280614
github.com/minio/sha256-simd
mkdir -p $WORK/github.com/minio/sha256-simd/_obj/
mkdir -p $WORK/github.com/minio/
cd /Users/zchee/go/src/github.com/minio/sha256-simd
/usr/local/go/pkg/tool/darwin_amd64/compile -o $WORK/github.com/minio/sha256-simd.a -trimpath $WORK -p github.com/minio/sha256-simd -buildid 31acf96442447949d090d6452699f16c8b28750e -D _/Users/zchee/go/src/github.com/minio/sha256-simd -I $WORK -pack -asmhdr $WORK/github.com/minio/sha256-simd/_obj/go_asm.h ./cpuid.go ./cpuid_amd64.go ./sha256.go ./sha256blockAvx2_amd64.go ./sha256blockAvx_amd64.go ./sha256blockSsse_amd64.go ./sha256block_amd64.go ./sha256block_noasm.go
/usr/local/go/pkg/tool/darwin_amd64/asm -o $WORK/github.com/minio/sha256-simd/_obj/asm.o -trimpath $WORK -I $WORK/github.com/minio/sha256-simd/_obj/ -I /usr/local/go/pkg/include -D GOOS_darwin -D GOARCH_amd64 ./cpuid_amd64.s ./sha256blockAvx2_amd64.s ./sha256blockAvx_amd64.s ./sha256blockSsse_amd64.s
# github.com/minio/sha256-simd
duplicate constants
asm: symbol constants listed multiple times
```

I have not investigated yet, but I was just a clean installation of macOS today. So I think that it is not in the environment-dependent problems.
Maybe caused by Sierra kernel or go?

<details>
<summary>Environment</summary>
```sh
> go version
go version devel +2481481 Wed Oct 26 03:51:33 2016 +0000 darwin/amd64

> uname -a
Darwin 192.168.1.5 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin

> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323

> sysctl machdep.cpu
machdep.cpu.tsc_ccc.denominator: 0
machdep.cpu.tsc_ccc.numerator: 0
machdep.cpu.thread_count: 8
machdep.cpu.core_count: 4
machdep.cpu.address_bits.virtual: 48
machdep.cpu.address_bits.physical: 39
machdep.cpu.tlb.shared: 1024
machdep.cpu.tlb.data.small_level1: 64
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.inst.large: 8
machdep.cpu.cache.size: 256
machdep.cpu.cache.L2_associativity: 8
machdep.cpu.cache.linesize: 64
machdep.cpu.arch_perf.fixed_width: 48
machdep.cpu.arch_perf.fixed_number: 3
machdep.cpu.arch_perf.events: 0
machdep.cpu.arch_perf.events_number: 7
machdep.cpu.arch_perf.width: 48
machdep.cpu.arch_perf.number: 4
machdep.cpu.arch_perf.version: 3
machdep.cpu.xsave.extended_state1: 1 0 0 0
machdep.cpu.xsave.extended_state: 7 832 832 0
machdep.cpu.thermal.energy_policy: 1
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.package_thermal_intr: 1
machdep.cpu.thermal.fine_grain_clock_mod: 1
machdep.cpu.thermal.core_power_limits: 1
machdep.cpu.thermal.ACNT_MCNT: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.dynamic_acceleration: 1
machdep.cpu.thermal.sensor: 1
machdep.cpu.mwait.sub_Cstates: 270624
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.linesize_max: 64
machdep.cpu.mwait.linesize_min: 64
machdep.cpu.processor_flag: 5
machdep.cpu.microcode_version: 15
machdep.cpu.cores_per_package: 8
machdep.cpu.logical_per_package: 16
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT RDTSCP TSCI
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 HLE AVX2 BMI2 INVPCID RTM FPU_CSDS
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.brand: 0
machdep.cpu.signature: 263777
machdep.cpu.extfeature_bits: 142473169152
machdep.cpu.leaf7_feature_bits: 12219
machdep.cpu.feature_bits: 9221960262849657855
machdep.cpu.stepping: 1
machdep.cpu.extfamily: 0
machdep.cpu.extmodel: 4
machdep.cpu.model: 70
machdep.cpu.family: 6
machdep.cpu.brand_string: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
machdep.cpu.vendor: GenuineIntel
machdep.cpu.max_ext: 2147483656
machdep.cpu.max_basic: 13
```
</details>

This problem also has `minio/minio` because depends on `minio/sha256-simd`.

**Comment by harshavardhana** [comment]
> /usr/local/go/pkg/tool/darwin_amd64/compile -o $WORK/github.com/minio/sha256-simd.a -trimpath $WORK -p github.com/minio/sha256-simd -buildid 31acf96442447949d090d6452699f16c8b28750e -D _/Users/zchee/go/src/github.com/minio/sha256-simd -I $WORK -pack -asmhdr $WORK/github.com/minio/sha256-simd/_obj/go_asm.h ./cpuid.go ./cpuid_amd64.go ./sha256.go ./sha256blockAvx2_amd64.go ./sha256blockAvx_amd64.go ./sha256blockSsse_amd64.go ./sha256block_amd64.go ./sha256block_noasm.go
> /usr/local/go/pkg/tool/darwin_amd64/asm -o $WORK/github.com/minio/sha256-simd/_obj/asm.o -trimpath $WORK -I $WORK/github.com/minio/sha256-simd/_obj/ -I /usr/local/go/pkg/include -D GOOS_darwin -D GOARCH_amd64 ./cpuid_amd64.s ./sha256blockAvx2_amd64.s ./sha256blockAvx_amd64.s ./sha256blockSsse_amd64.s
> # github.com/minio/sha256-simd
> duplicate constants
> asm: symbol constants listed multiple times

Sierra already seems to have broken some applications already.  This isn't surprising - have you seen this error in 10.11.x ?

**Comment by zchee** [comment]
@harshavardhana Yeah, I know. Apple has been major changes in the Sierra...

> have you seen this error in 10.11.x ?

I had never seen.
And, I've said did a clean install, but actually wanted to downgrade `10.12.0` from `10.12.1 beta 5` because `dlv` no longer work by changing the mach kernel internal.
So I haven't use El Capitan for a long time.

I forgot whether the installed the `minio/minio` on Sierra developer beta, but I will kernel debugging using the VMWare now, I test together.

BTW, Please tell me just for reference,
```sh
duplicate constants
asm: symbol constants listed multiple times
```
Where there is a possibility that occurs the error?

**Comment by harshavardhana** [comment]
> BTW, Please tell me just for reference (for debug),
> 
> duplicate constants
> asm: symbol constants listed multiple times
> Where there is a possibility that occurs the error on the code?

Which Golang version are you using?

**Comment by zchee** [comment]
@harshavardhana Ah, did you see my environment on ▶︎(`details`) pull down?

Please click ▶︎ button on the my first issue comment.
> ▶︎ Environment

**Comment by harshavardhana** [comment]
Can you not use "devel" version @zchee ? please use the stable release version like 1.7.3?

**Comment by zchee** [comment]
@harshavardhana I have tested and surprised, that's Go core bug. Yes, does not error use 1.7.3.
I'll post this problem to golang repository and mention to here. I will leave whether the closing this issue.
Sorry for confused.

**Comment by calmh** [comment]
I don't think this is a Go bug, as the symbols in question are in fact duplicated. This path, for example, resolves it:

```diff
diff --git a/sha256blockAvx_amd64.s b/sha256blockAvx_amd64.s
index 512e3cf..dfc7f4a 100644
--- a/sha256blockAvx_amd64.s
+++ b/sha256blockAvx_amd64.s
@@ -402,8 +402,3 @@ DATA shuf00BA<>+0x08(SB)/8, $0xFFFFFFFFFFFFFFFF
 
 DATA shufDC00<>+0x00(SB)/8, $0xFFFFFFFFFFFFFFFF
 DATA shufDC00<>+0x08(SB)/8, $0x0b0a090803020100
-
-GLOBL constants<>(SB), 8, $256
-GLOBL bflipMask<>(SB), (NOPTR+RODATA), $16
-GLOBL shuf00BA<>(SB), (NOPTR+RODATA), $16
-GLOBL shufDC00<>(SB), (NOPTR+RODATA), $16
```

**Comment by zchee** [comment]
@calmh Ah, so just change the specification or compiler behavior?
@harshavardhana What do you think?

**Comment by harshavardhana** [comment]
> I don't think this is a Go bug, as the symbols in question are in fact duplicated. This patch, for example, resolves it:
> 
> diff --git a/sha256blockAvx_amd64.s b/sha256blockAvx_amd64.s
> index 512e3cf..dfc7f4a 100644
> --- a/sha256blockAvx_amd64.s
> +++ b/sha256blockAvx_amd64.s
> @@ -402,8 +402,3 @@ DATA shuf00BA<>+0x08(SB)/8, $0xFFFFFFFFFFFFFFFF
> 
>  DATA shufDC00<>+0x00(SB)/8, $0xFFFFFFFFFFFFFFFF
>  DATA shufDC00<>+0x08(SB)/8, $0x0b0a090803020100
> -
> -GLOBL constants<>(SB), 8, $256
> -GLOBL bflipMask<>(SB), (NOPTR+RODATA), $16
> -GLOBL shuf00BA<>(SB), (NOPTR+RODATA), $16
> -GLOBL shufDC00<>(SB), (NOPTR+RODATA), $16
> (Can probably drop the duplicate DATA definitions above as well.)

ping @fwessels

**Comment by fwessels** [comment]
Package works fine with both go 1.7.1 and 1.7.3 -- apparently latest go devel version errors out, not aware of any intended changes or whether this is a side effect that will go away again.

The `GLOBL` directive is a bit misleading as it is not global across ASM files (like globals as you are used to at higher level language). The `DATA` and `GLOBL` definitions are actually duplicated in `sha256blockAvx_amd64.s` and `sha256blockSsse_amd64.s` (and needed now, otherwise we would not have duplicated the code).

It would be nice to be able to go to a single definition, and maybe there is thus some work underway.

**Comment by zchee** [comment]
@fwessels Thanks, I'm looking forward to it.
Also, I'm interested in the Go internal changes.

For all: Don't worry, I did not yet create the issue to golang.

**Comment by calmh** [comment]
This is still an issue in 1.8beta1. I think you guys should either fix this or file a bug on Go if you believe the error is incorrect.

**Comment by harshavardhana** [comment]
Thanks @calmh for opening the bug.

**Comment by calmh** [comment]
Looks like a genuine assembler bug, so no worries on this side.

**Comment by fwessels** [comment]
Yes, we will take a look.
