### ISSUE TITLE
README is not clear on how to generate the unaccelerated test results

### ISSUE THREAD

**Issue by vielmetti** [minio/sha256-simd#14]
I am looking at ARMv8 benchmarking for the Cavium 96-core ARMv8 machine that Packet has as a 2A server. It's not clear from the README how to force the tests to be run to generate the unaccelerated results, so that I can do benchmark compares of accelerated vs unaccelerated.

thanks for any assistance, and I'll happily add a PR to the README with whatever gets settled on.

**Comment by alexellis** [comment]
@harshavardhana it would be great to have instructions to easily benchmark the following:

* Assembly-optimized sha256 algorithm
* Go's crypto/sha256 package

It would be good to add to the results to the table too.

**Comment by harshavardhana** [comment]
There is no easy way to fix this - what the current code does is enables capabilities automatically - this is same even for go's stdlib.  To run un-accelerated tests you need to locally modify the code to avoid auto detection.

**Comment by alexellis** [comment]
Maybe just give the instructions you guys used to run the original tests.

**Comment by fwessels** [comment]
Original tests were run without the assembly code available, so essentially removing the .s files for ARM will do the job. 

It would be interesting to see the results on Cavium, we have yet to test it ourselves.

**Comment by vielmetti** [comment]
OK, I modified the code to return false instead of doing auto-detection, and ran the code both with go 1.6.3 and with go 1.8rc3 both accelerated and unaccelerated on the Packet 2A server. Here's my results:

go 1.6.3, unaccelerated;
```
root@docker-build-test:/mnt/src/minio/sha256-simd# more old-nocpuid.txt 
PASS
BenchmarkHash8Bytes-96    200000              6268 ns/op           1.28 MB/s
BenchmarkHash1K-96         20000             94939 ns/op          10.79 MB/s
BenchmarkHash8K-96          2000            717869 ns/op          11.41 MB/s
BenchmarkHash1M-96            20          90904200 ns/op          11.53 MB/s
ok      _/mnt/src/minio/sha256-simd     7.630s
```

go 1.6.3, accelerated;
```
root@docker-build-test:/mnt/src/minio/sha256-simd# more old.txt
PASS
BenchmarkHash8Bytes-96   1000000              1020 ns/op           7.84 MB/s
BenchmarkHash1K-96        300000              4208 ns/op         243.31 MB/s
BenchmarkHash8K-96         50000             26893 ns/op         304.61 MB/s
BenchmarkHash1M-96           500           3301734 ns/op         317.58 MB/s
ok      _/mnt/src/minio/sha256-simd     5.983s
```

go 1.8rc3, not accelerated;
```
root@docker-build-test:/mnt/src/minio/sha256-simd# more new-go-1.8-nocpuid.txt 
BenchmarkHash8Bytes-96            500000              2790 ns/op           2.87 MB/s
BenchmarkHash1K-96                 50000             31608 ns/op          32.40 MB/s
BenchmarkHash8K-96                 10000            234781 ns/op          34.89 MB/s
BenchmarkHash1M-96                    50          29650586 ns/op          35.36 MB/s
PASS
ok      _/mnt/src/minio/sha256-simd     7.242s
```

go 1.8rc3, accelerated:
```
root@docker-build-test:/mnt/src/minio/sha256-simd# more new-go-1.8.txt 
BenchmarkHash8Bytes-96           2000000               710 ns/op          11.26 MB/s
BenchmarkHash1K-96                500000              3869 ns/op         264.63 MB/s
BenchmarkHash8K-96                 50000             26557 ns/op         308.46 MB/s
BenchmarkHash1M-96                   500           3300583 ns/op         317.69 MB/s
PASS
ok      _/mnt/src/minio/sha256-simd     7.732s
```

**Comment by vielmetti** [comment]
And while I'm here, the diff to turn off autodetect results in a function like so in cpuid_linux_arm64.go:

```
func haveArmSha() bool {
        // cpuInfo, err := ioutil.ReadFile(procCPUInfo)
        // if err != nil {
        //      return false
        // }
        // return bytes.Contains(cpuInfo, []byte(sha256Feature))
        return false
}
```

**Comment by fwessels** [comment]
Thank you for submitting these benchmarks, I ran them through `benchcmp` with the following results

go-1.6.3
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkHash8Bytes-96     6268          1020          -83.73%
BenchmarkHash1K-96         94939         4208          -95.57%
BenchmarkHash8K-96         717869        26893         -96.25%
BenchmarkHash1M-96         90904200      3301734       -96.37%

benchmark                  old MB/s     new MB/s     speedup
BenchmarkHash8Bytes-96     1.28         7.84         6.12x
BenchmarkHash1K-96         10.79        243.31       22.55x
BenchmarkHash8K-96         11.41        304.61       26.70x
BenchmarkHash1M-96         11.53        317.58       27.54x
```

and go-1.8rc3
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkHash8Bytes-96     2790          710           -74.55%
BenchmarkHash1K-96         31608         3869          -87.76%
BenchmarkHash8K-96         234781        26557         -88.69%
BenchmarkHash1M-96         29650586      3300583       -88.87%

benchmark                  old MB/s     new MB/s     speedup
BenchmarkHash8Bytes-96     2.87         11.26        3.92x
BenchmarkHash1K-96         32.40        264.63       8.17x
BenchmarkHash8K-96         34.89        308.46       8.84x
BenchmarkHash1M-96         35.36        317.69       8.98x
```

So there has definitely been a nice speed-up for the non-assembly version from approx 10-11 MB/s to 34-35 MB/s (at the time of our testing it was pretty much not optimized at all).

What puzzles me is that we found an overall max speed of up to 640 MB/s which is 2x more than what you are getting with the Cavium processor -- I would have expected this result...

**Comment by harshavardhana** [comment]
Would you mind pasting `cat /proc/cpuinfo` from Packet 2A host @vielmetti ?

**Comment by vielmetti** [comment]
See https://gist.github.com/d81912859fa1a26032c8e22f3af6bdc3

@harshavardhana

**Comment by harshavardhana** [comment]
> See https://gist.github.com/d81912859fa1a26032c8e22f3af6bdc3
> 
> @harshavardhana

Looks `sha1, sha2` we will validate it ourselves.  Hopefully packet has some servers available in stock :-)

**Comment by vielmetti** [comment]
OK, one more test: go 1.6.3 on CentOS 7.3 on the Packet 2A server:

```
[root@nrt-centos sha256-simd]# go test -bench=.
PASS
BenchmarkHash8Bytes-96   1000000              1039 ns/op           7.70 MB/s
BenchmarkHash1K-96        300000              4240 ns/op         241.48 MB/s
BenchmarkHash8K-96         50000             25686 ns/op         318.92 MB/s
BenchmarkHash1M-96           500           3320798 ns/op         315.76 MB/s
ok      _/root/src/minio/sha256-simd    5.941s
```

A tad faster than the same results on Ubuntu 16.04 on the same hardware. I'm still chasing down go 1.8 release on CentOS aarch64.

**Comment by harshavardhana** [comment]
Yes I did benchmarks and results are the same. These processors seemed to be perhaps a different ASIC design. This was mentioned on a call. So perhaps this is a maximum available still not bad with 10x improvement.  I guess we can attempt this again on OVH hardware .

**Comment by harshavardhana** [comment]
Closing this as a non issue, the ARM64 chipset is entirely different on Cavium with different ASIC so what we are getting right now is the best possible on those processors.
