### ISSUE TITLE
Further mips build things

### ISSUE THREAD

**Issue by calmh** [minio/sha256-simd#16]
I'd like to be able to build for `mipsle`, `mips64` and `mips64le` in addition to the just added `mips` support. Should I create files for all those, or take the opportunity to clean up the existing ppc and mips things into `..._unsupported` or `..._other` files with the appropriate build tags to avoid sprinkling hundreds of copies of the same files into the repo? :)

**Comment by harshavardhana** [comment]
keep it as _other would work @calmh
