### ISSUE TITLE
export function that detect SIMD instructions are available.

### ISSUE THREAD

**Issue by LeMoussel** [minio/sha256-simd#25]
for information, it would be interesting if the functions to detect if SIMD instructions are available were exported. 

For example, 
```
package main

import (
	"fmt"
	"encoding/hex"

	"./sha256-simd"
)

func main() {
	if sha256.HaveAVX2() {
		fmt.Println("AVX2 SIMD instructions available")
	}
}
```

**Comment by harshavardhana** [comment]
Feel free to copy the code into your project. IMO it is not a good idea for sha256-simd to have these as exported functions.

 // cc @fwessels what do you think ?

**Comment by fwessels** [comment]
I agree, this is best left out of the project.

**Comment by AudriusButkevicius** [comment]
Sorry for bringing up zombies, but it would be useful for AVX512, as there is now to know if that is supported.

**Comment by harshavardhana** [comment]
Feel free to send a PR we will review @AudriusButkevicius or use klauspost/cpuid package
