### ISSUE TITLE
How to calculate SHA224 checksum?

### ISSUE THREAD

**Issue by LeMoussel** [minio/sha256-simd#26]
Does this package implements  the SHA224 hash algorithms ?

Like crypto/sha256/sha256.go, [func New224()](https://golang.org/src/crypto/sha256/sha256.go?s=1773:1796#L79)
```
// New224 returns a new hash.Hash computing the SHA224 checksum.
func New224() hash.Hash { .... }
```

**Comment by harshavardhana** [comment]
This package is not meant for Sha224, please use the golang standard library @LeMoussel
