### ISSUE TITLE
Suggest to add a deprecation message in the readme

### ISSUE THREAD

**Issue by meling** [minio/sha256-simd#27]
I guess the project can be useful for people still on old versions of Go, but since Go 1.8 a similarly performing assembly implementation is available in the standard library. It would be helpful if the **readme** for this project had told me about this, preferably at the very top.

**Comment by AudriusButkevicius** [comment]
Your statement is false. Performance on ARM is nowhere close to the one this package provides.

**Comment by meling** [comment]
Well, then perhaps you should update the performance numbers for the amd64 (and ARM) architecture using Go 1.8/1.9 numbers for the standard lib versions. Otherwise, you are misrepresenting the standard library implementations as worse than they are.

**Comment by fwessels** [comment]
We will update the README to reflect that golang has caught up in terms of AVX2 performance.
