### ISSUE TITLE
Error when adding a copy method 

### ISSUE THREAD

**Issue by LeMoussel** [minio/sha256-simd#28]
I want to  adding a copy method direcly on sha256.digest,
In ` sha256.go` I do this 
```
// Copy returns a copy of hash.Hash
func (d *digest) Copy() hash.Hash {
	dCopy := *d
	return &dCopy
}
```

But when I build, this test program
```
package main
import (
	// https://github.com/minio/sha256-simd
	sha256simd "Test/sha256-simd"
)

func main() {
	d1 := sha256simd.New()
	d2 := sha256simd.New()

	d1.Write([]byte("a"))
	d2 = d1.Copy()
}
```
I got this error  `.\Main.go:15:9: d1.Copy undefined (type hash.Hash has no field or method Copy)`

**Comment by AudriusButkevicius** [comment]
hash.Hash interface does not have a .Copy, regardless that the underlying type implements it.

**Comment by fwessels** [comment]
That is correct, I guess you will need to copy it manually (or create your own wrapper around Hash).

**Comment by LeMoussel** [comment]
OK  I see it [hash.Hash](https://golang.org/src/hash/hash.go).
Some idea, on how to implement `copy` method?

**Comment by calmh** [comment]
I don't think you really want that copy method, either. What you might want is a function that copies state from one hasher to another without allocation, giving you more control over allocations when doing the copying.

**Comment by LeMoussel** [comment]
Yep , I want to calculate hash on 3 strings. First string is always the same, the other may vary.
The first approach is to calculate the hash each time for the 3 strings (`BenchmarkHash`)
Another approach would be to calculate once for the first string, and then reuse this hash to calculate the hash with the other 2 strings(`BenchmarkCopyHash`)
```
import (
	"bytes"
	"hash"
	"reflect"
	"strings"
	"testing"

	// https://github.com/minio/sha256-simd
	sha256simd "EggMiner/sha256-simd"
)

var m1 = strings.Repeat("a", 64)
var m2 = strings.Repeat("b", 48)
var m3 = strings.Repeat("c", 32)

var h1 []byte
var h2 []byte

func BenchmarkHash(b *testing.B) {
	var (
		d hash.Hash
	)

	d = sha256simd.New()
	for n := 0; n < b.N; n++ {
		d.Reset()
		d.Write([]byte(m1))
		d.Write([]byte(m2))
		d.Write([]byte(m3))
		h1 = d.Sum(h1[:0])
	}
}

func BenchmarkCopyHash(b *testing.B) {
	var (
		d1 hash.Hash
		d2 hash.Hash
	)

	d1 = sha256simd.New()
	d1.Write([]byte(m1))
	d2 = sha256simd.New()

	for n := 0; n < b.N; n++ {
               => How to copies state from d1 hasher to d2?
		d2.Write([]byte(m2))
		d2.Write([]byte(m3))
		h2 = d2.Sum(h2[:0])
	}

	if !bytes.Equal(h1, h2) {
		b.Fatalf("hash failure %x != %x", h1, h2)
	}
}
```

**Comment by AudriusButkevicius** [comment]
```
d1 = sha256simd.New()
if copyableD1, ok := d1.(interface {
   Copy() hash.Hash
}); ok {
   d1copy := copyableD1.Copy()
}
```
