### ISSUE TITLE
adds MarshalBinary and UnmarshalBinary

### ISSUE THREAD

**Issue by LeMoussel** [minio/sha256-simd#29]
Go 1.10 adds MarshalBinary and UnmarshalBinary to each of the hash.Hash implementations.
Réf: [crypto, hash: implement BinaryMarshaler, BinaryUnmarshaler in hash implementations](https://go-review.googlesource.com/c/go/+/66710)
[Example (BinaryMarshaler)](https://tip.golang.org/pkg/hash/#example__binaryMarshaler)

**Comment by harshavardhana** [comment]
Once go1.10 is released we will follow.

**Comment by AudriusButkevicius** [comment]
This was not added to the hash.Hash interface, but was just added to the underlying implementation, so to me it seems this is completely voluntary, and has to be verified by a interface assertion regardless.

**Comment by harshavardhana** [comment]
> This was not added to the hash.Hash interface, but was just added to the underlying implementation, so to me it seems this is completely voluntary, and has to be verified by a interface assertion regardless.

Ah that is good to know, we don't need to do anything on our end.
