### ISSUE TITLE
builds / tests fail on every architecture except x86_64

### ISSUE THREAD

**Issue by decathorpe** [minio/sha256-simd#31]
`go test github.com/minio/sha256-simd` fails on all fedora architectures except x86_64 due to the following error:

```
# github.com/minio/sha256-simd
(...)/src/github.com/minio/sha256-simd/sha256_test.go:2612:10: undefined: maskRounds
FAIL	github.com/minio/sha256-simd [build failed]
```

I myself am not familiar enough with go to point to the source of the problem, but it looks like the support for AVX512 introduced compilation errors due to some missing definitions on other architectures.

**Comment by fwessels** [comment]
Thanks for reporting, we will fix it ASAP

**Comment by fwessels** [comment]
Moved the AVX512 specific testing code to an amd64 specific test code file. This should address the issue.

**Comment by decathorpe** [comment]
It does, AFAICT. Thanks for responding so quickly!
