### ISSUE TITLE
go get error with gccgo

### ISSUE THREAD

**Issue by ddreyer** [minio/sha256-simd#41]
`go get -compiler gccgo -u github.com/minio/sha256-simd` fails with many errors of the following form:

`github.com/minio/sha256-simd/sha256blockAvx2_amd64.s:1432: Error: too many memory references for 'mov'`

Am I doing something wrong or is gccgo not supported?

**Comment by harshavardhana** [comment]
> `go get -compiler gccgo -u github.com/minio/sha256-simd` fails with many errors of the following form:
> 
> `github.com/minio/sha256-simd/sha256blockAvx2_amd64.s:1432: Error: too many memory references for 'mov'`
> 
> Am I doing something wrong or is gccgo not supported?

We don't support gccgo - there is no reason to use it just do `go get`

**Comment by kannappanr** [comment]
@ddreyer Closing this issue based on the previous comment. Please feel free to reach out to us if you have further questions.
