### ISSUE TITLE
how to use these codes?

### ISSUE THREAD

**Issue by irocn** [minio/sha256-simd#53]
I have a server with cpu flags avx2. I want to accelerate the sha256 computing speed. Could anybody tell me how to use it?

**Comment by AudriusButkevicius** [comment]
It's in the readme of the repo?

**Comment by irocn** [comment]
@AudriusButkevicius I think I should use blockAvx2 function, but I don't find it's implemention.
and It output follow error information when I compile the sha256blockAvx2_amd64.s .
....
sha256blockAvx2_amd64.s:1398: Error: no such instruction: `long $0xf07b63c4'
sha256blockAvx2_amd64.s:1398: Error: invalid character '$' in mnemonic
sha256blockAvx2_amd64.s:1399: Error: no such instruction: `long $0x00048d45//lea r8d,[r8+rax*1]'
sha256blockAvx2_amd64.s:1400: Error: invalid character '$' in mnemonic
sha256blockAvx2_amd64.s:1400: Error: no such instruction: `byte $0xff//and r15d,edi'
sha256blockAvx2_amd64.s:1401: Error: invalid character '$' in mnemonic
sha256blockAvx2_amd64.s:1401: Error: no such instruction: `byte $0xe6//xor r14d,r12d'
sha256blockAvx2_amd64.s:1402: Error: invalid character '$' in mnemonic
sha256blockAvx2_amd64.s:1402: Error: no such instruction: `byte $0xcf//xor r15d,ecx'
sha256blockAvx2_amd64.s:1403: Error: invalid character '$' in mnemonic
sha256blockAvx2_amd64.s:1403: Error: no such instruction: `byte $0xee//xor r14d,r13d'
sha256blockAvx2_amd64.s:1404: Error: no such instruction: `long $0x38048d42//lea eax,[rax+r15*1]'
sha256blockAvx2_amd64.s:1405: Error: invalid character '$' in mnemonic
sha256blockAvx2_amd64.s:1405: Error: no such instruction: `byte $0xcc//mov r12d,r9d'
sha256blockAvx2_amd64.s:1408: Error: too many memory references for `cmp'
sha256blockAvx2_amd64.s:1411: Error: junk `(SP)' after expression
sha256blockAvx2_amd64.s:1411: Error: too many memory references for `movq'
sha256blockAvx2_amd64.s:1412: Error: too many memory references for `add'
sha256blockAvx2_amd64.s:1416: Error: too many memory references for `add'
sha256blockAvx2_amd64.s:1417: Error: junk `(DI)' after expression
sha256blockAvx2_amd64.s:1417: Error: too many memory references for `add'
sha256blockAvx2_amd64.s:1418: Error: junk `(DI)' after expression
sha256blockAvx2_amd64.s:1418: Error: too many memory references for `add'
sha256blockAvx2_amd64.s:1419: Error: junk `(DI)' after expression
sha256blockAvx2_amd64.s:1419: Error: too many memory references for `add'
sha256blockAvx2_amd64.s:1420: Error: junk `(DI)' after expression
sha256blockAvx2_amd64.s:1420: Error: too many memory references for `add'
.....

**Comment by AudriusButkevicius** [comment]
You should just go get the package and use it as shown in the readme:

```go
import "github.com/minio/sha256-simd"

func main() {
        ...
	shaWriter := sha256.New()
	io.Copy(shaWriter, file)
        ...
}
```
