### ISSUE TITLE
Illegal instruction crash on ARM64

### ISSUE THREAD

**Issue by calmh** [minio/sha256-simd#6]
It seems that `Amlogic ARM® Cortex®-A53(ARMv8) 1.5Ghz` CPUs are misdetected somehow, causing a SIGILL on these systems. The crashing instruction is [here](https://github.com/minio/sha256-simd/blob/master/sha256block_arm64.s#L59). I don't have one of these myself, but can probably extract relevant info if you suggest what's needed and how to get it. :)

(Relates to https://github.com/syncthing/syncthing/issues/3613)

**Comment by harshavardhana** [comment]
We will take a look. Thanks @calmh

**Comment by calmh** [comment]
Also, on this proc/cpuinfo output:

```
processor   : 0
BogoMIPS    : 48.00
Features    : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant : 0x0
CPU part    : 0xd03
CPU revision    : 4

processor   : 1
BogoMIPS    : 48.00
Features    : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant : 0x0
CPU part    : 0xd03
CPU revision    : 4

processor   : 2
BogoMIPS    : 48.00
Features    : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant : 0x0
CPU part    : 0xd03
CPU revision    : 4

processor   : 3
BogoMIPS    : 48.00
Features    : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant : 0x0
CPU part    : 0xd03
CPU revision    : 4

Hardware    : ODROID-C2
Revision    : 020b
```

**Comment by xor-gate** [comment]
Any progress on this?

**Comment by calmh** [comment]
Also,

```
Machine: Odroid-c2 (Raspberry-PI like mini computer) 
CPU: Amlogic S905 : Quad Core Cortex™-A53 (ARMv8 64bit) processor with Triple Core Mali-450 GPU
```

**Comment by harshavardhana** [comment]
@calmh do you have any server / machine where this can be verified?

**Comment by calmh** [comment]
Nope, these are all from reports from various users out there on the internet. I lack any similar hardware. But I can probably reach out to the reporters and have them test and collect more data etc if necessary.

**Comment by harshavardhana** [comment]
Looks like I found a way there are no cpuid instructions like x86 for feature detection. Will send a patch today thanks for following up @calmh

**Comment by calmh** [comment]
Sweet, thanks.

**Comment by xor-gate** [comment]
Looks good to me!
