### ISSUE TITLE
Go 1.7 implemented AVX2 support should we do ARM64 support upstream? 

### ISSUE THREAD

**Issue by harshavardhana** [minio/sha256-simd#7]
https://golang.org/src/crypto/sha256/sha256block_amd64.s , we should also update the benchmarks.

**Comment by ncw** [comment]
I think you should upstream the ARMv8 code.  I wrote the assembly support for MD5 and SHA1 for ARM 32 bit and I found the experience interacting with the go team very positive.  I think for a 100x speedup they would be very interested!

**Comment by harshavardhana** [comment]
> I think you should upstream the ARMv8 code. I wrote the assembly support for MD5 and SHA1 for ARM 32 bit and I found the experience interacting with the go team very positive. I think for a 100x speedup they would be very interested!

That is the plan @ncw

**Comment by ncw** [comment]
Have you looked at the ARMv8 AES instruction too?

**Comment by fwessels** [comment]
@ncw We need to do some code cleanup, esp. on the Intel side as this was still developed under Go 1.6 before a lot of new AVX instructions were introduced in 1.7.

Regarding ARM we are first going to look at PMULL (polynomial arithmetic) to speed up Erasure Coding. AES would be interesting too -- do you have a specific need for this?

**Comment by ncw** [comment]
@fwessels I've had a complaint about the speed of SSL with rclone on ARMv8: https://github.com/ncw/rclone/issues/1013 - using the AES instruction would help greatly!  That probably affects minio too.

**Comment by fwessels** [comment]
@ncw We haven't had the complaint thus far, but it would most likely affect minio too. Are you aware whether there is maybe any ARM sample code out there that could potentially be ported?

Although it would be fun to do, too be honest, it is not high on our priority list, so don't expect anything soon...

**Comment by vielmetti** [comment]
I'm happy to help wrangle sample code and look for testbed resource to do and to benchmark this work.

**Comment by fwessels** [comment]
@vielmetti That would be great, I did a quick browse around and here is a pointer to some sample code to maybe get you started: 
- https://github.com/openssl/openssl/blob/master/crypto/aes/asm/aesv8-armx.pl 

(note that this is actually a perl script which, when executed, generates the actual assembly file to go through the assembler)

Let us know if you would have any further questions, we'd be happy to help.

**Comment by gaillard** [comment]
Would also love the arm64 AES support here or upstream :)

**Comment by vielmetti** [comment]
I cross-linked the upstream issue https://github.com/golang/go/issues/18498 to identify folks who are working on and interested in this.

**Comment by fwessels** [comment]
@vielmetti Thank you for the cross-post, we were not aware of this one.

**Comment by vielmetti** [comment]
Thanks @fwessels . I also note @williamweixiao comments in https://github.com/golang/go/issues/19715#issuecomment-289376221 as relevant

**Comment by williamweixiao** [comment]
yes, we (arm enterprise language team) have planned to optimize hash, crypto and runtime with armv8 SIMD instructions this year. since most optimizations will be implemented by assembly and upstream hopes us to add the missing disassembler first to enhance the assembler test for future adding new instructions (https://github.com/golang/go/issues/18070).
we are now working at developing arm64 decoder which is expected to be ready next month. after that we will start optimizing CRC, AES and runtime utility functions.
welcome to sync with us about optimizing golang for arm64.

**Comment by kannappanr** [comment]
Will revisit this work on to upstream our implementation at a later date, closing this issue for now.
