### ISSUE TITLE
Integrate with google/oss-fuzz

### ISSUE THREAD

**Issue by nathaniel-brough** [minio/sha256-simd#70]
Hey I'd like to suggest adding sha256-simd to google/oss-fuzz. If you aren't familiar with fuzz testing, here is a bit of a run down ([from Wikipedia](https://en.wikipedia.org/wiki/Fuzzing));

> In [programming](https://en.wikipedia.org/wiki/Computer_programming) and [software development](https://en.wikipedia.org/wiki/Software_development), fuzzing or fuzz testing is an automated [software testing](https://en.wikipedia.org/wiki/Software_testing) technique that involves providing invalid, unexpected, or [random data](https://en.wikipedia.org/wiki/Random_data) as inputs to a [computer program](https://en.wikipedia.org/wiki/Computer_program). The program is then monitored for exceptions such as [crashes](https://en.wikipedia.org/wiki/Crash_(computing)), failing built-in code [assertions](https://en.wikipedia.org/wiki/Assertion_(software_development)), or potential [memory leaks](https://en.wikipedia.org/wiki/Memory_leak).

Google offers a free continuous fuzzing service called OSS-fuzz. If sha256-simd is integrated into oss-fuzz, the fuzz tests under sha256-simd will be built and then run once a day, to search for bugs and vulnerabilities in sha256-simd. This service can be integrated with the CI for sha256-simd, so that the fuzz tests are run for 10min or so for every pull request, preventing buggy code from being merged.

I've opened up a pull request to add a basic fuzz-testing harness here https://github.com/minio/sha256-simd/pull/69. If you are keen on adding sha256-simd to oss-fuzz I'd be happy to champion the integration :)

**Comment by klauspost** [comment]
I don't think this package has a long life ahead of itself, now that https://github.com/golang/go/issues/50543 is merged into Go.

So YES to adding the fuzz test. NO to adding it to ossfuzz.
