### ISSUE TITLE
`NewAvx512Server` is undefined // AVX 512

### ISSUE THREAD

**Issue by jbrower95** [minio/sha256-simd#73]
I want to use AVX512 to speed up some parallel SHA256 hash calculations for a Merkle proof. I have some sample code right now that is computing hashes across many goroutines. We're running this code on an AWS EC2 with AVX512 support.

What's up with building? My go.mod file has v1.0.1 (github.com/minio/sha256-simd v1.0.1) but even just including

```
	server := sha256.NewAvx512Server()
	h512 := sha256.NewAvx512(server)
```

is leading to `undefined: sha256.NewAvx512Server`

A few questions:
- Are these functions conditionally-compiled out, based on architecture?
- The `server` object should be shared across threads, but `h512` should be created 1 per goroutine? Just want to understand the threading model a bit better.
- Is there a compatibility mode for preserving source code on platforms that don't support AVX512? It would be really nice if I didn't need to conditionally-compile on my end too, and `sha256.NewAvx512` could just transparently route to the correct implementation on non-compliant platforms.

So many questions. Thanks for reading this!

**Comment by klauspost** [comment]
> Are these functions conditionally-compiled out, based on architecture?

The functions are only available on `amd64`, so your code must have build tags for that.

> The server object should be shared across threads, but h512 should be created 1 per goroutine? Just want to understand the threading model a bit better.

`NewAvx512Server()` -> shared server.
`NewAvx512(a512srv *Avx512Server) hash.Hash` -> one encode stream.

> Is there a compatibility mode

No.
