### ISSUE TITLE
Support for Xeon Phi AVX512 instructions

### ISSUE THREAD

**Issue by sigkill** [minio/sha256-simd#74]
I know they're getting removed soon from support, but am curious if this project supports the AVX512 instructions for the 72XX (7210 to 7295) Intel KNL / KNM processor family?

How hard would it be to add support?

**Comment by klauspost** [comment]
@sigkill What are you thinking off specifically wrt SHA256?

**Comment by fwessels** [comment]
We have never tested the AVX512 implementation on a Xeon Phi or Knights Landing/Mill board, however since it supports AVX512 it should work.

Note that the AVX512 code is derived originally from Intel code (see README), so one could imagine that Intel would have run it on one of those boards.

If you have access to a board, you could give it a try ...

**Comment by sigkill** [comment]
Unfortunately, there is some assembly present that is outside of the supported instructions on the Xeon Phi 7295 and 7210 (Knights Landing, Knights Mill)

I attempted to patch last night, but it's not something I know well.

```
--- original_sha256blockAvx512_amd64.asm
+++ knights_mill_sha256blockAvx512_amd64.asm
@@ -273,7 +273,7 @@
    LEAQ PSHUFFLE_TRANSPOSE16_MASK1<>(SB), BX \
    LEAQ PSHUFFLE_TRANSPOSE16_MASK2<>(SB), R8 \
                                      \
    vmovdqu32 _r14, [rbx]            \
-   vpermi2q  _r14, _t0, _r2         \ // r14 = {h8  g8  f8  e8   d8  c8  b8  a8   h0 g0 f0 e0   d0 c0 b0 a0}
+   vshuff64x2 _r14, _t0, _r2, 0xEE  \ // r14 = {h8  g8  f8  e8   d8  c8  b8  a8   h0 g0 f0 e0   d0 c0 b0 a0}
    vmovdqu32 _t1,  [r8]             \
-   vpermi2q  _t1,  _t0, _r2         \ // t1  = {h12 g12 f12 e12  d12 c12 b12 a12  h4 g4 f4 e4   d4 c4 b4 a4}
+   vshuff64x2 _t1,  _t0, _r2, 0x44  \ // t1  = {h12 g12 f12 e12  d12 c12 b12 a12  h4 g4 f4 e4   d4 c4 b4 a4}
                                      \
    vmovdqu32 _r2, [rbx]             \
-   vpermi2q  _r2, _r3, _r7          \ // r2  = {h9  g9  f9  e9   d9  c9  b9  a9   h1 g1 f1 e1   d1 c1 b1 a1}
+   vshuff64x2 _r2, _r3, _r7, 0xEE   \ // r2  = {h9  g9  f9  e9   d9  c9  b9  a9   h1 g1 f1 e1   d1 c1 b1 a1}
    vmovdqu32 _t0, [r8]              \
-   vpermi2q  _t0, _r3, _r7          \ // t0  = {h13 g13 f13 e13  d13 c13 b13 a13  h5 g5 f5 e5   d5 c5 b5 a5}
+   vshuff64x2 _t0, _r3, _r7, 0x44   \ // t0  = {h13 g13 f13 e13  d13 c13 b13 a13  h5 g5 f5 e5   d5 c5 b5 a5}
                                      \
    vmovdqu32 _r3, [rbx]             \
-   vpermi2q  _r3, _r1, _r5          \ // r3  = {h10 g10 f10 e10  d10 c10 b10 a10  h2 g2 f2 e2   d2 c2 b2 a2}
+   vshuff64x2 _r3, _r1, _r5, 0xEE   \ // r3  = {h10 g10 f10 e10  d10 c10 b10 a10  h2 g2 f2 e2   d2 c2 b2 a2}
    vmovdqu32 _r7, [r8]              \
-   vpermi2q  _r7, _r1, _r5          \ // r7  = {h14 g14 f14 e14  d14 c14 b14 a14  h6 g6 f6 e6   d6 c6 b6 a6}
+   vshuff64x2 _r7, _r1, _r5, 0x44   \ // r7  = {h14 g14 f14 e14  d14 c14 b14 a14  h6 g6 f6 e6   d6 c6 b6 a6}
                                      \
    vmovdqu32 _r1, [rbx]             \
-   vpermi2q  _r1, _r0, _r4          \ // r1  = {h11 g11 f11 e11  d11 c11 b11 a11  h3 g3 f3 e3   d3 c3 b3 a3}
+   vshuff64x2 _r1, _r0, _r4, 0xEE   \ // r1  = {h11 g11 f11 e11  d11 c11 b11 a11  h3 g3 f3 e3   d3 c3 b3 a3}
    vmovdqu32 _r5, [r8]              \
-   vpermi2q  _r5, _r0, _r4          \ // r5  = {h15 g15 f15 e15  d15 c15 b15 a15  h7 g7 f7 e7   d7 c7 b7 a7}
+   vshuff64x2 _r5, _r0, _r4, 0x44   \ // r5  = {h15 g15 f15 e15  d15 c15 b15 a15  h7 g7 f7 e7   d7 c7 b7 a7}
                                      \
    vmovdqu32 _r0, [rbx]             \
-   vpermi2q  _r0, _r6, _r10         \ // r0  = {p8  o8  n8  m8   l8  k8  j8  i8   p0 o0 n0 m0   l0 k0 j0 i0}
+   vshuff64x2 _r0, _r6, _r10, 0xEE  \ // r0  = {p8  o8  n8  m8   l8  k8  j8  i8   p0 o0 n0 m0   l0 k0 j0 i0}
    vmovdqu32 _r4, [r8]              \
-   vpermi2q  _r4, _r6, _r10         \ // r4  = {p12 o12 n12 m12  l12 k12 j12 i12  p4 o4 n4 m4   l4 k4 j4 i4}
+   vshuff64x2 _r4, _r6, _r10, 0x44  \ // r4  = {p12 o12 n12 m12  l12 k12 j12 i12  p4 o4 n4 m4   l4 k4 j4 i4}
                                      \
    vmovdqu32 _r6, [rbx]             \
-   vpermi2q  _r6, _r11, _r15        \ // r6  = {p9  o9  n9  m9   l9  k9  j9  i9   p1 o1 n1 m1   l1 k1 j1 i1}
+   vshuff64x2 _r6, _r11, _r15, 0xEE \ // r6  = {p9  o9  n9  m9   l9  k9  j9  i9   p1 o1 n1 m1   l1 k1 j1 i1}
    vmovdqu32 _r10, [r8]             \
-   vpermi2q  _r10, _r11, _r15       \ // r10 = {p13 o13 n13 m13  l13 k13 j13 i13  p5 o5 n5 m5   l5 k5 j5 i5}
+   vshuff64x2 _r10, _r11, _r15, 0x44 \ // r10 = {p13 o13 n13 m13  l13 k13 j13 i13  p5 o5 n5 m5   l5 k5 j5 i5}
                                      \
    vmovdqu32 _r11, [rbx]            \
-   vpermi2q  _r11, _r9, _r13        \ // r11 = {p10 o10 n10 m10  l10 k10 j10 i10  p2 o2 n2 m2   l2 k2 j2 i2}
+   vshuff64x2 _r11, _r9, _r13, 0xEE \ // r11 = {p10 o10 n10 m10  l10 k10 j10 i10  p2 o2 n2 m2   l2 k2 j2 i2}
    vmovdqu32 _r15, [r8]             \
-   vpermi2q  _r15, _r9, _r13        \ // r15 = {p14 o14 n14 m14  l14 k14 j14 i14  p6 o6 n6 m6   l6 k6 j6 i6}
+   vshuff64x2 _r15, _r9, _r13, 0x44 \ // r15 = {p14 o14 n14 m14  l14 k14 j14 i14  p6 o6 n6 m6   l6 k6 j6 i6}
                                      \
    vmovdqu32 _r9, [rbx]             \
-   vpermi2q  _r9, _r8, _r12         \ // r9  = {p11 o11 n11 m11  l11 k11 j11 i11  p3 o3 n3 m3   l3 k3 j3 i3}
+   vshuff64x2 _r9, _r8, _r12, 0xEE  \ // r9  = {p11 o11 n11 m11  l11 k11 j11 i11  p3 o3 n3 m3   l3 k3 j3 i3}
    vmovdqu32 _r13, [r8]             \
-   vpermi2q  _r13, _r8, _r12        \ // r13 = {p15 o15 n15 m15  l15 k15 j15 i15  p7 o7 n7 m7   l7 k7 j7 i7}
+   vshuff64x2 _r13, _r8, _r12, 0x44 \ // r13 = {p15 o15 n15 m15  l15 k15 j15 i15  p7 o7 n7 m7   l7 k7 j7 i7}
```

**Comment by sigkill** [comment]
the AVX512 code doesn't seem like it's sticking to a specific instruction set - like avx512f, it seems like there may be a mix of different AVX512 instructions present.

"Looking at the sha256blockAvx512_amd64.asm code, here are a few instructions that would not be supported on KNL:

	•	vpmullq (part of AVX512DQ): Performs packed multiplication of quadwords.
	•	vpaddb and vpsubb (part of AVX512BW): Operate on byte-level operations.
	•	vpermb (part of AVX512VBMI): Permutes bytes in a vector according to a control mask.
	•	vexpandpd (part of AVX512VL): Expands packed double-precision floating-point elements."

**Comment by klauspost** [comment]
> the AVX512 code doesn't seem like it's sticking to a specific instruction set

That seems like a strange expectation.

These are the required types: https://github.com/minio/sha256-simd/blob/master/cpuid_other.go#L28 - should match your list.

The pipelined AVX512 has a very limited usage scope, and I am not sure how widely it is used, since the synchronization overhead typically outweighs the benefits, unless you already have all streams synchronized.

**Comment by sigkill** [comment]
Thank you for pointing that bit of code out! It looks like those are indeed for Skylake and a little more than just one type of AVX512, but a mix of some of the newer instruction sets mixed with some of the supported sets.

- AVX512F and AVX512VL are supported by the Intel Xeon Phi KNL/KNM architectures.

- AVX512DQ and AVX512BW are not supported by KNL/KNM and are instead supported by newer Intel architectures, such as Skylake-X and Cascade Lake.

Not sure if it would be possible to update the code to work with the Xeon Phi 7200 series of processors. I know it's an old and weird cpu, but for this use case it would be awesome to see a side by side comparison of what the 7295 is capable of.

**Comment by klauspost** [comment]
@sigkill If you are able to test it, feel free to send a PR.

**Comment by sigkill** [comment]
Will try, going to take me a bit to attempt it. My patch was not great.

**Comment by rs78GT** [comment]
@sigkill Is there any progress with this parallel SHA256 / AVX512 on Xeon Phi? Right now, I am just building a server with a 7250, and I am very interested in this topic too. Maybe I'm wrong, but if there is an "incomplete" instruction set for AVX512, the AVX2 is just working fine. That wouldn't be a bad trade considering the available number of cores! I would like to process only 4 independent messages in one go, so the AVX2 should be enough in my case.

Can we talk about this independently (somehow: mail, etc.), I don't want to disturb this topic, but very difficult to find someone, or any information around with the Xeon Phi's!

Thanks in advance!

**Comment by klauspost** [comment]
The missing instructions sigkill lists AFAICT makes this impossible. So I don't really see any reason to keep this open any more.

Feel free to make a PR, if you figure something out.
